version: 2
updates:
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: three
    versions:
    - 0.125.2
    - 0.126.0
    - 0.126.1
    - 0.127.0
  - dependency-name: electron
    versions:
    - 12.0.0
    - 12.0.1
    - 12.0.2
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.2
    - 2.3.1
  - dependency-name: sass-loader
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: "@sentry/integrations"
    versions:
    - 6.0.3
    - 6.1.0
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.3
    - 6.1.0
